# Generated by Django 5.0.7 on 2024-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('P', 'Proccessing'), ('S', 'Shipped'), ('D', 'Delivered')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True),
        ),
    ]
