# Generated by Django 5.0.7 on 2024-08-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shipment_status_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wishlists'},
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='item',
            new_name='product',
        ),
    ]
