# Generated by Django 5.0.7 on 2024-08-20 06:16

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_wishlist_options_rename_item_wishlist_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='store/images/category.png', upload_to='store/images/category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='/images/users/person.png', null=True, upload_to=store.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='store/images/product.png', upload_to='store/images/product'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, default='/images/users/person.png', null=True, upload_to=store.models.user_directory_path),
        ),
    ]
