# Generated by Django 5.0.7 on 2024-07-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_user_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
    ]
